# Generated by Django 3.2.1 on 2021-05-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horse_racing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(default='DEFAULT000', max_length=10)),
                ('created_on', models.DateTimeField()),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_for', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
