# Generated by Django 3.2.1 on 2021-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0004_horseracing_player_transactiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracing',
            name='horse1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='horseracing',
            name='horse2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='horseracing',
            name='horse3',
            field=models.IntegerField(default=0),
        ),
    ]
