# Generated by Django 3.2.1 on 2021-05-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0006_player_txn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='bin_name',
        ),
    ]
