# Generated by Django 3.2.1 on 2021-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0007_remove_transactiondetail_bin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='balance',
            field=models.CharField(default='20', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
