# Generated by Django 3.2.1 on 2021-05-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horse_racing', '0009_auto_20210515_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameplayhistory',
            name='result',
            field=models.CharField(default='Lose', max_length=10),
        ),
        migrations.DeleteModel(
            name='RechargeHistory',
        ),
    ]
