# Generated by Django 3.2.1 on 2021-05-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0010_auto_20210515_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayhistory',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horse_history', to='horse_racing.horseracing'),
        ),
        migrations.AddField(
            model_name='horseracing',
            name='winner',
            field=models.CharField(default='No One', max_length=10),
        ),
    ]
