# Generated by Django 3.2.1 on 2021-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0011_auto_20210516_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='win_balance',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
