# Generated by Django 3.2.1 on 2021-05-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0012_registration_win_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayhistory',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='horse_racing.player'),
        ),
    ]
