# Generated by Django 3.2.1 on 2021-05-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0013_gameplayhistory_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayhistory',
            name='player',
        ),
    ]
