# Generated by Django 3.2.1 on 2021-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0015_gameplayhistory_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayhistory',
            name='total_bet',
            field=models.IntegerField(default=0),
        ),
    ]
