# Generated by Django 3.2.1 on 2021-05-17 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horse_racing', '0019_alter_referral_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='balance',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('you_got', models.CharField(max_length=50)),
                ('which_horse', models.CharField(max_length=20)),
                ('referred_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_history', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_history', to='horse_racing.registration')),
            ],
        ),
    ]
